// This file is no longer needed.
// The service worker is now automatically generated by 'vite-plugin-pwa' during the build process.
// This ensures file hashes are correct and all assets are cached properly.